import json, os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
BASE=os.environ['E2E_BASE_URL'].rstrip('/')
env={}
for line in Path('.env.local').read_text(encoding='utf-8-sig').splitlines():
    if '=' in line: k,v=line.split('=',1); env[k]=v.strip().strip('"').strip("'")
for k in ('E2E_VIEWER_A_EMAIL','E2E_VIEWER_A_PASSWORD','E2E_SUSPENDED_A_EMAIL','E2E_SUSPENDED_A_PASSWORD'):
    if os.getenv(k): env[k]=os.environ[k]
marker='phase121b-'+str(os.getpid()); report={'base':BASE,'errors':[],'5xx':[]}
def login(ctx,email,password):
    r=ctx.request.post(BASE+'/api/auth/login',form={'email':email,'password':password,'next':'/dashboard'})
    assert 200<=r.status<300, r.status
def api(page,path,method='GET',body=None):
    return page.evaluate("""async x=>{let r=await fetch(x.path,{method:x.method,credentials:'include',headers:x.body?{'content-type':'application/json'}:undefined,body:x.body?JSON.stringify(x.body):undefined});let b=null;try{b=await r.json()}catch{}return {status:r.status,body:b}}""",{'path':path,'method':method,'body':body})
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,args=['--no-sandbox']); ctx=browser.new_context(viewport={'width':1366,'height':900},extra_http_headers={'x-vercel-protection-bypass':env['VERCEL_AUTOMATION_BYPASS_SECRET']}); page=ctx.new_page()
    page.on('console',lambda m:report['errors'].append('console:'+m.text) if m.type=='error' else None); page.on('pageerror',lambda e:report['errors'].append('pageerror:'+str(e))); page.on('response',lambda r:report['5xx'].append(r.url) if r.status>=500 else None)
    login(ctx,env['E2E_OWNER_A_EMAIL'],env['E2E_OWNER_A_PASSWORD']); page.goto(BASE+'/produtos',wait_until='domcontentloaded'); page.wait_for_timeout(1200); page.get_by_role('button',name='Novo produto').click(); page.locator('input[placeholder="Nome"]').fill(marker+' Product'); page.locator('input[placeholder="Preço"]').fill('1000'); page.get_by_role('button',name='Salvar').click(); page.wait_for_timeout(1000); page.reload(); page.wait_for_timeout(1000); expect(page.get_by_text(marker+' Product',exact=True).first).to_be_visible(); report['product_create_refresh']=True
    page.get_by_text(marker+' Product',exact=True).first.locator('xpath=ancestor::tr').get_by_role('button',name='Editar').click(); page.locator('input[placeholder="Preço"]').fill('1500'); page.get_by_role('button',name='Salvar').click(); page.wait_for_timeout(800); page.reload(); page.wait_for_timeout(800); report['product_edit_refresh']=page.get_by_text('R$ 1.500,00').first.count()==1
    page.on('dialog',lambda d:d.accept()); page.get_by_role('button',name='Arquivar').first.click(); page.wait_for_timeout(700); page.reload(); page.wait_for_timeout(700); report['product_archive_refresh']=page.get_by_text(marker+' Product',exact=True).count()==0
    page.goto(BASE+'/propostas',wait_until='domcontentloaded'); page.wait_for_timeout(1200); page.get_by_role('button',name='Nova proposta').click(); page.get_by_role('combobox').first.select_option(index=1); page.locator('input[placeholder="Título"]').fill(marker+' Proposal'); page.get_by_role('button',name='Adicionar item').click(); page.get_by_label('Descrição do item 1').fill(marker+' Item One'); page.get_by_label('Preço do item 1').fill('1000'); page.get_by_label('Quantidade do item 1').fill('2'); page.get_by_label('Descrição do item 2').fill(marker+' Item Two'); page.get_by_label('Preço do item 2').fill('0.01'); page.get_by_role('button',name='Criar proposta').click(); page.wait_for_timeout(1200); report['proposal_create']=page.get_by_text(marker+' Proposal',exact=True).count()==1; report['multiple_items']=page.get_by_text(marker+' Item One',exact=True).count()==1 and page.get_by_text(marker+' Item Two',exact=True).count()==1; page.get_by_role('button',name='Remover item 2').click(); page.wait_for_timeout(900); page.reload(); page.wait_for_timeout(900); report['remove_item_refresh']=page.get_by_text(marker+' Item Two',exact=True).count()==0
    page.get_by_role('button',name='Marcar enviada').click(); page.wait_for_timeout(700); page.reload(); page.wait_for_timeout(700); report['status_sent']=page.get_by_text('sent',exact=True).count()>0; page.get_by_role('button',name='Aceitar').click(); page.wait_for_timeout(700); page.reload(); page.wait_for_timeout(700); report['status_accepted']=page.get_by_text('accepted',exact=True).count()>0
    page.goto(BASE+'/negocios',wait_until='domcontentloaded'); page.wait_for_timeout(1200); deal=api(page,'/api/commercial/deals')['body']['deals'][0]['id']; page.get_by_test_id('deal-row-'+deal).click(); page.wait_for_timeout(700); page.get_by_text('Produtos',exact=True).click(); page.wait_for_timeout(700); report['deal_drawer']=page.get_by_text('Propostas persistentes',exact=True).count()==1
    for width in (390,1366): page.set_viewport_size({'width':width,'height':844}); page.goto(BASE+'/produtos',wait_until='domcontentloaded'); page.wait_for_timeout(700); report['viewport_'+str(width)]=page.evaluate('document.documentElement.scrollWidth<=window.innerWidth')
    for role,ek,pk in [('viewer','E2E_VIEWER_A_EMAIL','E2E_VIEWER_A_PASSWORD'),('suspended','E2E_SUSPENDED_A_EMAIL','E2E_SUSPENDED_A_PASSWORD')]:
        rc=browser.new_context(viewport={'width':1366,'height':900},extra_http_headers={'x-vercel-protection-bypass':env['VERCEL_AUTOMATION_BYPASS_SECRET']}); rp=rc.new_page(); login(rc,env[ek],env[pk]); rp.goto(BASE+'/produtos',wait_until='domcontentloaded'); rp.wait_for_timeout(900); get=api(rp,'/api/commercial/products'); write=api(rp,'/api/commercial/products','POST',{'name':marker+' blocked','unit_price':1}); report[role]={'read':get['status'],'write_blocked':write['status']>=400,'write_ui_hidden':rp.get_by_role('button',name='Novo produto').count()==0}; rc.close()
    report['favicon']=ctx.request.get(BASE+'/favicon.ico').status; print(json.dumps(report,ensure_ascii=False,indent=2)); browser.close()
