import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "../../types/database.types";
import type { ActivityItem } from "../../types/crm";
type Client = SupabaseClient<Database>;
type Row = Database["public"]["Tables"]["activities"]["Row"];
function mapActivity(row: Row, ownerName = row.owner_id || "Sem responsÃ¡vel"): ActivityItem { return { id: row.id, organizationId: row.organization_id, type: row.type as ActivityItem["type"], title: row.title, description: row.description || undefined, ownerId: row.owner_id || "", ownerName, startAt: row.start_at, endAt: row.end_at || undefined, entityType: row.entity_type as ActivityItem["entityType"], entityId: row.entity_id || undefined, status: row.status as ActivityItem["status"], createdAt: row.created_at, updatedAt: row.updated_at, archivedAt: row.archived_at }; }
async function names(client: Client, ids: (string | null)[]) { const unique = [...new Set(ids.filter((id): id is string => Boolean(id)))]; if (!unique.length) return new Map<string,string>(); const { data } = await client.from("profiles").select("id, full_name").in("id", unique); return new Map((data || []).map((item) => [item.id, item.full_name || item.id])); }
export async function listActivities(client: Client, organizationId: string, from?: string, to?: string) { let query = client.from("activities").select("*").eq("organization_id", organizationId).is("archived_at", null).order("start_at", { ascending: true }); if (from) query = query.gte("start_at", from); if (to) query = query.lte("start_at", to); const { data, error } = await query; if (error) throw error; const owners = await names(client, (data || []).map((row) => row.owner_id)); return (data || []).map((row) => mapActivity(row, row.owner_id ? owners.get(row.owner_id) : undefined)); }
export async function getActivity(client: Client, organizationId: string, id: string) { const { data, error } = await client.from("activities").select("*").eq("organization_id", organizationId).eq("id", id).maybeSingle(); if (error) throw error; return data ? mapActivity(data) : null; }
export async function createActivity(client: Client, organizationId: string, userId: string, input: Partial<ActivityItem>) { const { data, error } = await client.from("activities").insert({ organization_id: organizationId, created_by: userId, type: input.type || "meeting", title: input.title?.trim() || "Nova atividade", description: input.description || null, status: "scheduled", start_at: input.startAt || new Date().toISOString(), end_at: input.endAt || null, owner_id: input.ownerId || userId, entity_type: input.entityType || null, entity_id: input.entityId || null }).select("*").single(); if (error) throw error; return mapActivity(data); }
export async function updateActivity(client: Client, organizationId: string, id: string, input: Partial<ActivityItem>) { const payload: Database["public"]["Tables"]["activities"]["Update"] = {}; if (input.type !== undefined) payload.type = input.type; if (input.title !== undefined) payload.title = input.title.trim(); if (input.description !== undefined) payload.description = input.description || null; if (input.startAt !== undefined) payload.start_at = input.startAt; if (input.endAt !== undefined) payload.end_at = input.endAt || null; if (input.ownerId !== undefined) payload.owner_id = input.ownerId || null; const { data, error } = await client.from("activities").update(payload).eq("organization_id", organizationId).eq("id", id).select("*").single(); if (error) throw error; return mapActivity(data); }
async function status(client: Client, organizationId: string, id: string, value: string) { const { data, error } = await client.from("activities").update({ status: value }).eq("organization_id", organizationId).eq("id", id).select("*").single(); if (error) throw error; return mapActivity(data); }
export const completeActivity = (client: Client, org: string, id: string) => status(client, org, id, "completed");
export const cancelActivity = (client: Client, org: string, id: string) => status(client, org, id, "cancelled");
export async function archiveActivity(client: Client, organizationId: string, id: string) { const { data, error } = await client.from("activities").update({ archived_at: new Date().toISOString() }).eq("organization_id", organizationId).eq("id", id).select("*").single(); if (error) throw error; return mapActivity(data); }
