"use client";
import { useEffect, useMemo, useState } from "react";
import { Check, Clock3, Pause, Play, Plus, RefreshCw, ShieldCheck, Trash2 } from "lucide-react";

type Automation = { id: string; name: string; description: string | null; status: string; trigger_type: string; conditions: unknown[]; actions: unknown[] };
type FollowUp = { id: string; entity_type: string; entity_id: string; type: string; status: string; scheduled_for: string };
const triggerLabels: Record<string, string> = { "deal.stage_changed": "Negócio muda de etapa", "deal.won": "Negócio ganho", "deal.lost": "Negócio perdido", "lead.created": "Lead criado" };

export function AutomationsPage() {
  const [automations, setAutomations] = useState<Automation[]>([]); const [followUps, setFollowUps] = useState<FollowUp[]>([]); const [runs, setRuns] = useState<Record<string, unknown[]>>({});
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editing, setEditing] = useState<Automation | null>(null); const [tab, setTab] = useState<"automations" | "followups">("automations"); const [dryRunMessage, setDryRunMessage] = useState("");
  const [form, setForm] = useState({ name: "", description: "", triggerType: "deal.stage_changed", threshold: "10000", actionTitle: "Criar follow-up do negócio", days: "2" });
  const [followForm, setFollowForm] = useState({ entityType: "deal", entityId: "", type: "reminder", scheduledFor: "" });
  const load = async () => { setLoading(true); setError(""); try { const [a, f] = await Promise.all([fetch("/api/automations"), fetch("/api/follow-ups")]); if (!a.ok || !f.ok) throw new Error("Não foi possível carregar o módulo"); setAutomations((await a.json()).automations || []); setFollowUps((await f.json()).followUps || []); } catch (e) { setError(e instanceof Error ? e.message : "Erro inesperado"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const summary = useMemo(() => `Quando ${triggerLabels[form.triggerType] || form.triggerType} e valor > R$ ${Number(form.threshold || 0).toLocaleString("pt-BR")} criar tarefa em ${form.days} dias.`, [form]);
  async function save(event: React.FormEvent) { event.preventDefault(); const payload = { name: form.name, description: form.description, triggerType: form.triggerType, conditions: [{ field: "value", operator: "gt", value: Number(form.threshold) }], actions: [{ type: "create_task", title: form.actionTitle, days: Number(form.days) }] }; const response = await fetch(editing ? `/api/automations/${editing.id}` : "/api/automations", { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) { setError("Não foi possível salvar a automação"); return; } setEditing(null); setForm({ name: "", description: "", triggerType: "deal.stage_changed", threshold: "10000", actionTitle: "Criar follow-up do negócio", days: "2" }); await load(); }
  async function changeStatus(item: Automation, status: string) { await fetch(`/api/automations/${item.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); await load(); }
  async function showRuns(id: string) { const response = await fetch(`/api/automations/${id}/runs`); const body = await response.json(); setRuns((old) => ({ ...old, [id]: body.runs || [] })); }
  async function dryRun(item: Automation) { const response = await fetch(`/api/automations/${item.id}/dry-run`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ value: Number(form.threshold), pipeline_id: "preview", stage_id: "preview" }) }); const body = await response.json(); setDryRunMessage(body.dryRun ? `Dry-run: ${body.dryRun.matches ? "as condições seriam atendidas" : "as condições não seriam atendidas"}. Nenhum dado foi alterado.` : "Dry-run indisponível."); }
  async function followUpStatus(id: string, status: "completed" | "cancelled") { await fetch(`/api/follow-ups/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); await load(); }
  async function createManualFollowUp(event: React.FormEvent) { event.preventDefault(); const response = await fetch("/api/follow-ups", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...followForm, scheduledFor: new Date(followForm.scheduledFor).toISOString() }) }); if (!response.ok) { setError("Não foi possível criar o follow-up. Confirme o ID da entidade."); return; } setFollowForm({ entityType: "deal", entityId: "", type: "reminder", scheduledFor: "" }); await load(); }
  return <section className="space-y-5" data-testid="automations-page">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Operação segura</p><h1 className="text-2xl font-black text-slate-900 sm:text-3xl">Automações e Follow-ups</h1><p className="mt-1 text-sm text-slate-500">Regras server-side, auditáveis e sem envio externo.</p></div><button onClick={() => { setTab("automations"); setEditing(null); }} className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white"><Plus size={16}/> Nova automação</button></div>
    <div className="flex gap-2 border-b border-slate-200"><button onClick={() => setTab("automations")} className={`px-4 py-2 text-sm font-bold ${tab === "automations" ? "border-b-2 border-indigo-600 text-indigo-700" : "text-slate-500"}`}>Automações</button><button onClick={() => setTab("followups")} className={`px-4 py-2 text-sm font-bold ${tab === "followups" ? "border-b-2 border-indigo-600 text-indigo-700" : "text-slate-500"}`}>Follow-ups ({followUps.filter((x) => x.status === "scheduled").length})</button></div>
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}{dryRunMessage && <div className="rounded-xl border border-indigo-200 bg-indigo-50 p-3 text-sm text-indigo-800">{dryRunMessage}</div>}{loading ? <div className="rounded-2xl bg-white p-8 text-center text-slate-500"><RefreshCw className="mx-auto mb-2 animate-spin"/>Carregando dados reais...</div> : tab === "automations" ? <div className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]">
      <div className="space-y-3">{automations.length === 0 && <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><ShieldCheck className="mx-auto mb-3 text-indigo-500"/><h2 className="font-bold text-slate-900">Nenhuma automação ativa</h2><p className="mt-1 text-sm text-slate-500">Esta organização começa vazia e segura.</p></div>}{automations.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm" data-testid={`automation-${item.id}`}><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><h2 className="font-extrabold text-slate-900">{item.name}</h2><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${item.status === "active" ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{item.status}</span></div><p className="mt-1 text-sm text-slate-500">{triggerLabels[item.trigger_type] || item.trigger_type}</p><p className="mt-2 text-xs text-slate-400">{item.actions.length} ação(ões) · condições validadas no servidor</p></div><div className="flex flex-wrap gap-2"><button onClick={() => { setEditing(item); setForm({ name: item.name, description: item.description || "", triggerType: item.trigger_type, threshold: "10000", actionTitle: "Criar tarefa", days: "2" }); }} className="rounded-lg border px-2.5 py-1.5 text-xs font-bold">Editar</button>{item.status === "active" ? <button aria-label="Pausar automação" onClick={() => void changeStatus(item, "paused")} className="rounded-lg border px-2.5 py-1.5 text-xs font-bold"><Pause size={13}/></button> : <button aria-label="Ativar automação" onClick={() => void changeStatus(item, "active")} className="rounded-lg border px-2.5 py-1.5 text-xs font-bold"><Play size={13}/></button>}<button onClick={() => void dryRun(item)} className="rounded-lg border px-2.5 py-1.5 text-xs font-bold">Dry-run</button><button onClick={() => void showRuns(item.id)} className="rounded-lg border px-2.5 py-1.5 text-xs font-bold">Execuções</button></div></div>{runs[item.id] && <div className="mt-3 border-t pt-3 text-xs text-slate-500">{runs[item.id].length ? runs[item.id].map((run, index) => <div key={index} className="flex justify-between py-1"><span>Evento processado</span><span className="font-bold">{String((run as { status?: string }).status)}</span></div>) : "Nenhuma execução."}</div>}</article>)}</div>
      <form onSubmit={save} className="h-fit space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><h2 className="font-extrabold text-slate-900">{editing ? "Editar regra" : "Builder básico"}</h2><p className="mt-1 text-xs text-slate-500">Trigger → condições → ação</p></div><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Nome da automação" className="w-full rounded-xl border px-3 py-2.5 text-sm"/><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Descrição opcional" className="w-full rounded-xl border px-3 py-2.5 text-sm"/><label className="block text-xs font-bold text-slate-600">Trigger<select value={form.triggerType} onChange={(e) => setForm({ ...form, triggerType: e.target.value })} className="mt-1 w-full rounded-xl border px-3 py-2.5 text-sm"><option value="deal.stage_changed">Negócio muda de etapa</option><option value="deal.won">Negócio ganho</option><option value="deal.lost">Negócio perdido</option><option value="lead.created">Lead criado</option></select></label><label className="block text-xs font-bold text-slate-600">Valor mínimo<input type="number" value={form.threshold} onChange={(e) => setForm({ ...form, threshold: e.target.value })} className="mt-1 w-full rounded-xl border px-3 py-2.5 text-sm"/></label><label className="block text-xs font-bold text-slate-600">Título da tarefa<input required value={form.actionTitle} onChange={(e) => setForm({ ...form, actionTitle: e.target.value })} className="mt-1 w-full rounded-xl border px-3 py-2.5 text-sm"/></label><label className="block text-xs font-bold text-slate-600">Dias até o follow-up<input type="number" min="0" max="365" value={form.days} onChange={(e) => setForm({ ...form, days: e.target.value })} className="mt-1 w-full rounded-xl border px-3 py-2.5 text-sm"/></label><div className="rounded-xl bg-indigo-50 p-3 text-xs leading-5 text-indigo-800">{summary}</div><button type="submit" className="w-full rounded-xl bg-indigo-600 py-2.5 text-sm font-bold text-white">{editing ? "Salvar alterações" : "Criar como rascunho"}</button></form>
    </div> : <div className="space-y-4"><form onSubmit={createManualFollowUp} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-4"><select value={followForm.entityType} onChange={(e) => setFollowForm({ ...followForm, entityType: e.target.value })} className="rounded-xl border px-3 py-2.5 text-sm"><option value="deal">Negócio</option><option value="lead">Lead</option><option value="contact">Contato</option><option value="company">Empresa</option></select><input required value={followForm.entityId} onChange={(e) => setFollowForm({ ...followForm, entityId: e.target.value })} placeholder="ID da entidade" className="rounded-xl border px-3 py-2.5 text-sm"/><input required type="datetime-local" value={followForm.scheduledFor} onChange={(e) => setFollowForm({ ...followForm, scheduledFor: e.target.value })} className="rounded-xl border px-3 py-2.5 text-sm"/><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-3 py-2.5 text-sm font-bold text-white"><Plus size={15}/> Criar follow-up</button></form><div className="grid gap-3 sm:grid-cols-2">{followUps.length === 0 && <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500 sm:col-span-2">Nenhum follow-up nesta organização.</div>}{followUps.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-bold text-slate-900">{item.type === "reminder" ? "Lembrete interno" : "Follow-up"}</h2><p className="text-xs text-slate-500">{item.entity_type} · {item.entity_id.slice(0, 8)}</p><p className="mt-2 flex items-center gap-1 text-xs text-slate-500"><Clock3 size={13}/>{new Date(item.scheduled_for).toLocaleString("pt-BR")}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase">{item.status}</span></div>{item.status === "scheduled" && <div className="mt-3 flex gap-2"><button onClick={() => void followUpStatus(item.id, "completed")} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-bold text-white"><Check size={13}/> Concluir</button><button onClick={() => void followUpStatus(item.id, "cancelled")} className="inline-flex items-center gap-1 rounded-lg border px-3 py-1.5 text-xs font-bold"><Trash2 size={13}/> Cancelar</button></div>}</article>)}</div></div>}
  </section>;
}
